[package]
name = "rgsl-nlinear"
version = "0.1.0"
edition = "2021"

[build-dependencies]
cc = "1.0"
pkg-config = "0.3"

[dependencies]
GSL-sys = { version = "3.0.0", path = "../gsl-sys" }

[lib]
name = "rgsl_nlinear"
crate-type = ["dylib", "rlib"]
